version: "3.8"

services:
  credit-risk-api:
    build: .
    container_name: credit-risk-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
    volumes:
      - ./data:/app/data
      - ./mlflow.db:/app/mlflow.db
      - ./logs:/app/logs
    networks:
      - credit-risk-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add MLflow UI service
  mlflow-ui:
    image: python:3.10-slim
    container_name: mlflow-ui
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
    volumes:
      - ./mlflow.db:/app/mlflow.db
    working_dir: /app
    command: >
      sh -c "pip install mlflow &&
             mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db"
    networks:
      - credit-risk-network
    depends_on:
      - credit-risk-api

networks:
  credit-risk-network:
    driver: bridge

volumes:
  mlflow-data:
