version: "3.8"
services:
  app:
    build: .
    container_name: credit-risk-model-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      ["uvicorn", "src/api/main:app", "--host", "0.0.0.0", "--port", "8000"]
